FROM adoptopenjdk/openjdk11-openj9:jre-nightly

WORKDIR /work
RUN chmod 777 /work
ADD  --chown=1001:0 QuarkusFiles/lib.tar.gz /work/
ADD  --chown=1001:0 QuarkusFiles/rest-http-crud-quarkus-1.0.0.Alpha1-SNAPSHOT-runner.jar.tar.gz /work
COPY --chown=1001:0 scriptToRunInsideDocker.sh /work/scriptToRunInsideDocker.sh
COPY --chown=1001:0 populate_scc.sh /work/populate_scc.sh

EXPOSE 8080
ENV JAVA_OPTS "$JAVA_OPTS -Djava.net.preferIPv4Stack=true"
# HOST is the node where postgress runs
ENV HOST=localhost
RUN ./populate_scc.sh

ENTRYPOINT ["/work/scriptToRunInsideDocker.sh"]
