# Dockerfile to build a jmeter container able to drive acmeair
# Results appear on /output in the container
# Must specify the hostname for the acmeair application (or localhost will be assumed)

FROM adoptopenjdk/openjdk8-openj9:jre

ENV JMETER_VERSION 3.3

# Install pre-requisite packages
RUN apt-get update && apt-get install -y --no-install-recommends wget unzip \
       && rm -rf /var/lib/apt/lists/*

# Install jmeter 
RUN   mkdir /jmeter \
        && mkdir /output \
        && cd /jmeter/ \
        && wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
        && tar -xzf apache-jmeter-$JMETER_VERSION.tgz \ 
        && rm apache-jmeter-$JMETER_VERSION.tgz 

# Set jmeter home, add jmeter to the PATH and set JVM options
ENV JMETER_HOME="/jmeter/apache-jmeter-$JMETER_VERSION"

# Add jmeter to the PATH
ENV PATH="$JMETER_HOME/bin:$PATH"

# Set JVM options
ENV JVM_ARGS "-Xms1g -Xmx1g -Xtune:virtualized"

# We should set summariser.interval=6 in bin/jmeter.properties and also allow cookies
RUN echo 'summariser.interval=6' >> $JMETER_HOME/bin/jmeter.properties
RUN echo 'CookieManager.save.cookies=true' >> $JMETER_HOME/bin/jmeter.properties


# Copy the script to be executed and other needed files
COPY DriverFiles/AcmeAir-microservices-mpJwt.jmx $JMETER_HOME/AcmeAir-microservices-mpJwt.jmx
COPY DriverFiles/Airports.csv $JMETER_HOME/Airports.csv
COPY DriverFiles/Airports2.csv $JMETER_HOME/Airports2.csv
COPY DriverFiles/hosts.csv $JMETER_HOME/hosts.csv
COPY DriverFiles/json-simple-1.1.1.jar $JMETER_HOME/lib/ext/
COPY DriverFiles/acmeair-jmeter-2.0.0-SNAPSHOT.jar $JMETER_HOME/lib/ext/
COPY DriverFiles/applyLoad.sh $JMETER_HOME/bin/applyLoad.sh
RUN chmod u+x $JMETER_HOME/bin/applyLoad.sh

# Environment variables that we want the user to redefine
ENV JHOST=localhost \
    JPORT=9090 \
    JUSERBOTTOM=0 \
    JUSER=199 \
    JURL=acmeair \
    JTHREAD=15 \
    JDURATION=60 \
    JRAMP=0

ENTRYPOINT ["applyLoad.sh"]
#jmeter -n -DusePureIDs=true -t AcmeAir-microservices-mpJwt.jmx -j /output/acmeair.stats.0 -JHOST=$JHOST -JPORT=$JPORT -JUSERBOTTOM=$JUSERBOTTOM -JUSER=$JUSER -JURL=$JURL -JTHREAD=$JTHREAD -JDURATION=$JDURATION -JRAMP=$JRAMP


