# Dockerfile to build a jmeter container able to drive quarkus crud app
# Results appear on /output in the container
# Must specify the hostname for the acmeair application (or localhost will be assumed)

FROM adoptopenjdk/openjdk8-openj9:jre

ENV JMETER_VERSION 3.3

# Install pre-requisite packages
RUN apt-get update && apt-get install -y --no-install-recommends wget unzip \
       && rm -rf /var/lib/apt/lists/*

# Install jmeter 
RUN   mkdir /jmeter \
        && mkdir /output \
        && cd /jmeter/ \
        && wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
        && tar -xzf apache-jmeter-$JMETER_VERSION.tgz \ 
        && rm apache-jmeter-$JMETER_VERSION.tgz 

# Set jmeter home 
ENV JMETER_HOME  /jmeter/apache-jmeter-$JMETER_VERSION 

# Add jmeter to the PATH  
ENV PATH $JMETER_HOME/bin:$PATH 

# Set JVM options
ENV JVM_ARGS "-Xms1g -Xmx1g -Xtune:virtualized"

# We should set summariser.interval=6 in bin/jmeter.properties
RUN echo 'summariser.interval=6' >> $JMETER_HOME/bin/jmeter.properties

# Copy the script to be executed and other needed files
COPY DriverFiles/jmeter_restcrud.quarkus.jmx $JMETER_HOME/jmeter_restcrud.quarkus.jmx
COPY DriverFiles/applyLoad.sh $JMETER_HOME/bin/applyLoad.sh
RUN chmod u+x $JMETER_HOME/bin/applyLoad.sh


# Environment variables that we want the user to redefine
ENV JHOST=localhost JPORT=8080 JTHREADS=1 JDURATION=60 JRAMP=0 JTHINKTIME=0 JROOT="/quarkuscrud"

ENTRYPOINT ["applyLoad.sh"]

