FROM ibm-semeru-runtimes:open-11.0.17_8-jre-focal

RUN mkdir -p /vlogs
RUN chown 1001:0 /vlogs

WORKDIR /work
COPY --chown=1001:0 spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar application.jar
EXPOSE 8080
USER 1001:0

COPY --chown=1001:0 populate_scc.sh populate_scc.sh
RUN ./populate_scc.sh

# Setup the SCC options matching the system SCC name/location present in IBM Semeru Runtimes
ENV OPENJ9_JAVA_OPTIONS="-Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc"

CMD ["java", "-jar", "application.jar"]

