# Dockerfile used for creating a container capable to run DT7 
FROM adoptopenjdk/openjdk11-openj9:x86_64-ubuntu-jre11u-nightly as JRE
FROM openliberty/open-liberty:21.0.0.3-kernel-slim-java11-openj9-ubi

USER root

# Delete original SDK
RUN rm -rf /opt/java  /output/.classCache

# Copy the JITServer SDK
COPY --from=JRE --chown=1001:0  /opt/java /opt/java

COPY --chown=1001:0 LibertyFiles/daytrader-ee7.ear /config/apps
COPY --chown=1001:0 LibertyFiles/bootstrap.properties /config/bootstrap.properties
COPY --chown=1001:0 LibertyFiles/server.xml /config/server.xml
COPY --chown=1001:0 LibertyFiles/db2 /opt/ol/wlp/usr/shared/resources/db2

# The following line is needed if "jre" directory does not exist
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH="/opt/java/openjdk/bin:${PATH}"
ENV db2ip="192.168.1.7"

USER 1001:0
ENV VERBOSE=true
#ENV OPENJ9_SCC=false
RUN features.sh
RUN configure.sh
RUN mkdir /tmp/vlogs 

