# Dockerfile to build a jmeter container able to drive acmeair
# Results appear on /output in the container
# Must specify the hostname for the acmeair application (or localhost will be assumed)

FROM adoptopenjdk/openjdk8-openj9:jre

ENV JMETER_VERSION 3.3

# Install pre-requisite packages
RUN apt-get update && apt-get install -y --no-install-recommends wget unzip \
       && rm -rf /var/lib/apt/lists/*

# Install jmeter 
RUN   mkdir /jmeter \
        && mkdir /output \
        && cd /jmeter/ \
        && wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
        && tar -xzf apache-jmeter-$JMETER_VERSION.tgz \ 
        && rm apache-jmeter-$JMETER_VERSION.tgz 

# Set jmeter home 
ENV JMETER_HOME  /jmeter/apache-jmeter-$JMETER_VERSION 

# Add jmeter to the PATH  
ENV PATH $JMETER_HOME/bin:$PATH 

# Set JVM options
ENV JVM_ARGS "-Xms1g -Xmx1g -Xtune:virtualized"

# We should set summariser.interval=6 in bin/jmeter.properties
RUN echo 'summariser.interval=6' >> $JMETER_HOME/bin/jmeter.properties

# Copy the script to be executed and other needed files
COPY DriverFiles/daytrader7.jmx $JMETER_HOME/daytrader7.jmx
COPY DriverFiles/jmeter-plugins-manager-0.16.jar $JMETER_HOME/lib/ext/
COPY DriverFiles/JMeterWebSocketSamplers-0.11.1.jar $JMETER_HOME/lib/ext/
COPY DriverFiles/applyLoad.sh $JMETER_HOME/bin/applyLoad.sh
RUN chmod u+x $JMETER_HOME/bin/applyLoad.sh


# Environment variables that we want the user to redefine
ENV JHOST=localhost JPORT=9080 JSTOCKS=9999 JBOTUID=0 JTOPUID=14999 JTHREADS=15 JDURATION=60 JRAMP=0 JMAXTHINKTIME=0

ENTRYPOINT ["applyLoad.sh"]
#"jmeter -n -t daytrader7.jmx -j /output/daytrader.stats -JHOST=$JHOST -JPORT=9090 -JSTOCKS=9999 -JBOTUID=0 -JTOPUID=14999 -JTHREADS=15 -JDURATION=600


